#!/usr/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# Definitions for configuration layout
# Change this to full path where the repo is placed
export DOTFILE_CONFIG_PATH=/etc/dotdotdot

# Definitions for XDG (See XDG Base Directory Specification)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# Editor defintions
export EDITOR="nvim"
export VISUAL="nvim"

# ZSH definitions
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

