#!/usr/bin/env zsh

# +------------+
# | NAVIGATION |
# +------------+
setopt AUTO_CD              # Go to folder path without using cd.

setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

setopt CORRECT              # Spelling correction
setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt EXTENDED_GLOB        # Use extended globbing syntax.

# +---------+
# | HISTORY |
# +---------+
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# +--------------------+
# | TIME NOTIFICATIONS |
# +--------------------+
# Send notification when command line done.
# source $DOTFILE_REPO_PATH/zsh/config/other/notifyosd.zsh

# +--------+
# | PROMPT |
# +--------+
source $DOTFILE_REPO_PATH/zsh/config/other/omz/nvm.zsh
source $DOTFILE_REPO_PATH/zsh/config/other/omz/bzr.zsh
source $DOTFILE_REPO_PATH/zsh/config/other/omz/theme-and-appearance.zsh
source $DOTFILE_REPO_PATH/zsh/config/other/omz/prompt_info_functions.zsh
source $DOTFILE_REPO_PATH/zsh/config/other/omz/async_prompt.zsh
source $DOTFILE_REPO_PATH/zsh/config/other/omz/git.zsh
# select theme
source $DOTFILE_REPO_PATH/zsh/config/other/omz/themes/gnzh

# +------------+
# | COMPLETION |
# +------------+
source $DOTFILE_REPO_PATH/zsh/config/other/completion.zsh

# +-----+
# | Git |
# +-----+
# Add command gitit to open Github repo in default browser from a local repo.
# source $DOTFILE_REPO_PATH/zsh/config/other/gitit.zsh

# +---------+
# | BINDING |
# +---------+
source $DOTFILE_REPO_PATH/zsh/config/other/bindings.zsh

# +-----+
# | FZF |
# +-----+
if [ $(command -v "fzf") ]; then
    if [ -f /usr/share/doc/fzf/examples/completion.zsh ]; then
        source /usr/share/doc/fzf/examples/completion.zsh
    fi
    if [ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]; then
        source /usr/share/doc/fzf/examples/key-bindings.zsh
    else
        echo $fg[red]"Couldn't find zsh keybindings for FZF."
    fi
else
    echo $fg[red]"Couldn't find the command 'fzf'."
fi

# +---------+
# | ALIASES |
# +---------+
source $DOTFILE_REPO_PATH/zsh/config/other/aliases.sh

# this must be last.
# +---------------------+
# | SYNTAX HIGHLIGHTING |
# +---------------------+
source $DOTFILE_REPO_PATH/zsh/config/other/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

